set_brightness:
  description: Set brightness without changing light state (only works for gen 2 lights)
  target:
    entity:
      domain: light
  fields:
    brightness:
      name: Brightness
      required: true
      description: Brightness (0 to 100)
      example: 75
      selector:
        number:
          min: 0
          max: 100

reconnect:
  description: Force a reconnect to the Lightwave backend

update_states:
  description: Force a read of all states of devices

reset_enabled_status_to_defaults:
  description: This will reset entities enabled statuses to defaults


