set_brightness:
  description: Set brightness without changing light state (only works for gen 2 lights)
  target:
    entity:
      domain: light
  fields:
    brightness:
      description: Brightness (0 to 255)
      example: 255