set_brightness:
  description: Set brightness without changing light state (only works for gen 2 lights)
  target:
    entity:
      domain: light
  fields:
    brightness:
      name: Brightness
      required: true
      description: Brightness (0 to 255)
      example: 255
      selector:
        number:
          min: 0
          max: 255