name: HACS Action

on:
  push:
  pull_request:
  schedule:
    - cron: "5 15 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"